-- AlterTable
ALTER TABLE "Animal" ADD COLUMN     "class" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "domain" TEXT,
ADD COLUMN     "family" TEXT,
ADD COLUMN     "scientificName" TEXT,
ADD COLUMN     "speed" DOUBLE PRECISION,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
